module Evergreen.Migrate.V2 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Array
import Dict
import Evergreen.V1.Block3d
import Evergreen.V1.BoundingBox3d
import Evergreen.V1.Cone3d
import Evergreen.V1.Cylinder3d
import Evergreen.V1.Geometry.Types
import Evergreen.V1.Internal.Body
import Evergreen.V1.Internal.Constraint
import Evergreen.V1.Internal.Contact
import Evergreen.V1.Internal.ContactCache
import Evergreen.V1.Internal.Coordinates
import Evergreen.V1.Internal.Equation
import Evergreen.V1.Internal.Material
import Evergreen.V1.Internal.Matrix3
import Evergreen.V1.Internal.Shape
import Evergreen.V1.Internal.Transform3d
import Evergreen.V1.Internal.Vector3
import Evergreen.V1.Internal.VertexBuffer
import Evergreen.V1.LineSegment3d
import Evergreen.V1.Physics
import Evergreen.V1.Physics.Types
import Evergreen.V1.Point3d
import Evergreen.V1.Polyline3d
import Evergreen.V1.Scene3d.Material
import Evergreen.V1.Scene3d.Mesh
import Evergreen.V1.Scene3d.Types
import Evergreen.V1.Shapes.Capsule
import Evergreen.V1.Shapes.Convex
import Evergreen.V1.Shapes.Plane
import Evergreen.V1.Shapes.Sphere
import Evergreen.V1.Sphere3d
import Evergreen.V1.Triangle3d
import Evergreen.V1.Types
import Evergreen.V1.Vector3d
import Evergreen.V2.Block3d
import Evergreen.V2.BoundingBox3d
import Evergreen.V2.Cone3d
import Evergreen.V2.Cylinder3d
import Evergreen.V2.Geometry.Types
import Evergreen.V2.Internal.Body
import Evergreen.V2.Internal.Constraint
import Evergreen.V2.Internal.Contact
import Evergreen.V2.Internal.ContactCache
import Evergreen.V2.Internal.Coordinates
import Evergreen.V2.Internal.Equation
import Evergreen.V2.Internal.Material
import Evergreen.V2.Internal.Matrix3
import Evergreen.V2.Internal.Shape
import Evergreen.V2.Internal.Transform3d
import Evergreen.V2.Internal.Vector3
import Evergreen.V2.Internal.VertexBuffer
import Evergreen.V2.LineSegment3d
import Evergreen.V2.Physics
import Evergreen.V2.Physics.Types
import Evergreen.V2.Point3d
import Evergreen.V2.Polyline3d
import Evergreen.V2.Scene3d.Material
import Evergreen.V2.Scene3d.Mesh
import Evergreen.V2.Scene3d.Types
import Evergreen.V2.Shapes.Capsule
import Evergreen.V2.Shapes.Convex
import Evergreen.V2.Shapes.Plane
import Evergreen.V2.Shapes.Sphere
import Evergreen.V2.Sphere3d
import Evergreen.V2.Triangle3d
import Evergreen.V2.Types
import Evergreen.V2.Vector3d
import Lamdera.Migrations exposing (..)
import List
import Maybe
import Quantity
import SeqSet
import TriangularMesh


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V2.Types.FrontendModel Evergreen.V2.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V2.Types.BackendModel Evergreen.V2.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V2.Types.FrontendMsg Evergreen.V2.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V2.Types.ToBackend Evergreen.V2.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V2.Types.BackendMsg Evergreen.V2.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V2.Types.ToFrontend Evergreen.V2.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V2.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , page = Evergreen.V2.Types.Home "" False
    , dimensions = old.dimensions
    , boxMesh = Nothing
    , boxMaterialRed = Nothing
    , boxMaterialBlue = Nothing
    , cylinderMesh = Nothing
    , letterBlocks = Dict.empty
    , setup = Evergreen.V2.Types.LoadFailure "There's been an update with new features, please reload"
    }


migrate_BoundingBox3d_BoundingBox3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.BoundingBox3d.BoundingBox3d units_old coordinates_old -> Evergreen.V2.BoundingBox3d.BoundingBox3d units_new coordinates_new
migrate_BoundingBox3d_BoundingBox3d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_BoundingBox3d


migrate_Cone3d_Cone3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Cone3d.Cone3d units_old coordinates_old -> Evergreen.V2.Cone3d.Cone3d units_new coordinates_new
migrate_Cone3d_Cone3d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_Cone3d migrate_units migrate_coordinates


migrate_Cylinder3d_Cylinder3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Cylinder3d.Cylinder3d units_old coordinates_old -> Evergreen.V2.Cylinder3d.Cylinder3d units_new coordinates_new
migrate_Cylinder3d_Cylinder3d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_Cylinder3d migrate_units migrate_coordinates


migrate_Geometry_Types_Axis3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Geometry.Types.Axis3d units_old coordinates_old -> Evergreen.V2.Geometry.Types.Axis3d units_new coordinates_new
migrate_Geometry_Types_Axis3d migrate_units migrate_coordinates old =
    case old of
        Evergreen.V1.Geometry.Types.Axis3d p0 ->
            Evergreen.V2.Geometry.Types.Axis3d
                { originPoint = p0.originPoint |> migrate_Geometry_Types_Point3d
                , direction = p0.direction |> migrate_Geometry_Types_Direction3d
                }


migrate_Geometry_Types_Block3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Geometry.Types.Block3d units_old coordinates_old -> Evergreen.V2.Geometry.Types.Block3d units_new coordinates_new
migrate_Geometry_Types_Block3d migrate_units migrate_coordinates old =
    case old of
        Evergreen.V1.Geometry.Types.Block3d p0 ->
            Evergreen.V2.Geometry.Types.Block3d
                { axes = p0.axes |> migrate_Geometry_Types_Frame3d migrate_units migrate_coordinates
                , dimensions = p0.dimensions |> (\( t1, t2, t3 ) -> ( t1 |> migrate_Quantity_Quantity, t2 |> migrate_Quantity_Quantity, t3 |> migrate_Quantity_Quantity ))
                }


migrate_Geometry_Types_BoundingBox3d : Evergreen.V1.Geometry.Types.BoundingBox3d units_old coordinates_old -> Evergreen.V2.Geometry.Types.BoundingBox3d units_new coordinates_new
migrate_Geometry_Types_BoundingBox3d old =
    case old of
        Evergreen.V1.Geometry.Types.BoundingBox3d p0 ->
            Evergreen.V2.Geometry.Types.BoundingBox3d p0


migrate_Geometry_Types_Cone3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Geometry.Types.Cone3d units_old coordinates_old -> Evergreen.V2.Geometry.Types.Cone3d units_new coordinates_new
migrate_Geometry_Types_Cone3d migrate_units migrate_coordinates old =
    case old of
        Evergreen.V1.Geometry.Types.Cone3d p0 ->
            Evergreen.V2.Geometry.Types.Cone3d
                { axis = p0.axis |> migrate_Geometry_Types_Axis3d migrate_units migrate_coordinates
                , radius = p0.radius |> migrate_Quantity_Quantity
                , length = p0.length |> migrate_Quantity_Quantity
                }


migrate_Geometry_Types_Cylinder3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Geometry.Types.Cylinder3d units_old coordinates_old -> Evergreen.V2.Geometry.Types.Cylinder3d units_new coordinates_new
migrate_Geometry_Types_Cylinder3d migrate_units migrate_coordinates old =
    case old of
        Evergreen.V1.Geometry.Types.Cylinder3d p0 ->
            Evergreen.V2.Geometry.Types.Cylinder3d
                { axis = p0.axis |> migrate_Geometry_Types_Axis3d migrate_units migrate_coordinates
                , radius = p0.radius |> migrate_Quantity_Quantity
                , length = p0.length |> migrate_Quantity_Quantity
                }


migrate_Geometry_Types_Direction3d : Evergreen.V1.Geometry.Types.Direction3d coordinates_old -> Evergreen.V2.Geometry.Types.Direction3d coordinates_new
migrate_Geometry_Types_Direction3d old =
    case old of
        Evergreen.V1.Geometry.Types.Direction3d p0 ->
            Evergreen.V2.Geometry.Types.Direction3d p0


migrate_Geometry_Types_Frame3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Geometry.Types.Frame3d units_old coordinates_old defines_old -> Evergreen.V2.Geometry.Types.Frame3d units_new coordinates_new defines_new
migrate_Geometry_Types_Frame3d migrate_units migrate_coordinates old =
    case old of
        Evergreen.V1.Geometry.Types.Frame3d p0 ->
            Evergreen.V2.Geometry.Types.Frame3d
                { originPoint = p0.originPoint |> migrate_Geometry_Types_Point3d
                , xDirection = p0.xDirection |> migrate_Geometry_Types_Direction3d
                , yDirection = p0.yDirection |> migrate_Geometry_Types_Direction3d
                , zDirection = p0.zDirection |> migrate_Geometry_Types_Direction3d
                }


migrate_Geometry_Types_LineSegment3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Geometry.Types.LineSegment3d units_old coordinates_old -> Evergreen.V2.Geometry.Types.LineSegment3d units_new coordinates_new
migrate_Geometry_Types_LineSegment3d migrate_units migrate_coordinates old =
    case old of
        Evergreen.V1.Geometry.Types.LineSegment3d p0 ->
            Evergreen.V2.Geometry.Types.LineSegment3d (p0 |> Tuple.mapBoth migrate_Geometry_Types_Point3d migrate_Geometry_Types_Point3d)


migrate_Geometry_Types_Point3d : Evergreen.V1.Geometry.Types.Point3d units_old coordinates_old -> Evergreen.V2.Geometry.Types.Point3d units_new coordinates_new
migrate_Geometry_Types_Point3d old =
    case old of
        Evergreen.V1.Geometry.Types.Point3d p0 ->
            Evergreen.V2.Geometry.Types.Point3d p0


migrate_Geometry_Types_Polyline3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Geometry.Types.Polyline3d units_old coordinates_old -> Evergreen.V2.Geometry.Types.Polyline3d units_new coordinates_new
migrate_Geometry_Types_Polyline3d migrate_units migrate_coordinates old =
    case old of
        Evergreen.V1.Geometry.Types.Polyline3d p0 ->
            Evergreen.V2.Geometry.Types.Polyline3d (p0 |> List.map migrate_Geometry_Types_Point3d)


migrate_Geometry_Types_Sphere3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Geometry.Types.Sphere3d units_old coordinates_old -> Evergreen.V2.Geometry.Types.Sphere3d units_new coordinates_new
migrate_Geometry_Types_Sphere3d migrate_units migrate_coordinates old =
    case old of
        Evergreen.V1.Geometry.Types.Sphere3d p0 ->
            Evergreen.V2.Geometry.Types.Sphere3d
                { centerPoint = p0.centerPoint |> migrate_Geometry_Types_Point3d
                , radius = p0.radius |> migrate_Quantity_Quantity
                }


migrate_Geometry_Types_Triangle3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Geometry.Types.Triangle3d units_old coordinates_old -> Evergreen.V2.Geometry.Types.Triangle3d units_new coordinates_new
migrate_Geometry_Types_Triangle3d migrate_units migrate_coordinates old =
    case old of
        Evergreen.V1.Geometry.Types.Triangle3d p0 ->
            Evergreen.V2.Geometry.Types.Triangle3d (p0 |> (\( t1, t2, t3 ) -> ( t1 |> migrate_Geometry_Types_Point3d, t2 |> migrate_Geometry_Types_Point3d, t3 |> migrate_Geometry_Types_Point3d )))


migrate_Geometry_Types_Vector3d : Evergreen.V1.Geometry.Types.Vector3d units_old coordinates_old -> Evergreen.V2.Geometry.Types.Vector3d units_new coordinates_new
migrate_Geometry_Types_Vector3d old =
    case old of
        Evergreen.V1.Geometry.Types.Vector3d p0 ->
            Evergreen.V2.Geometry.Types.Vector3d p0


migrate_Internal_Constraint_Constraint : Evergreen.V1.Internal.Constraint.Constraint coordinates_old -> Evergreen.V2.Internal.Constraint.Constraint coordinates_new
migrate_Internal_Constraint_Constraint old =
    case old of
        Evergreen.V1.Internal.Constraint.PointToPoint p0 p1 ->
            Evergreen.V2.Internal.Constraint.PointToPoint (p0 |> migrate_Internal_Vector3_Vec3)
                (p1 |> migrate_Internal_Vector3_Vec3)

        Evergreen.V1.Internal.Constraint.Hinge p0 p1 p2 p3 ->
            Evergreen.V2.Internal.Constraint.Hinge (p0 |> migrate_Internal_Vector3_Vec3)
                (p1 |> migrate_Internal_Vector3_Vec3)
                (p2 |> migrate_Internal_Vector3_Vec3)
                (p3 |> migrate_Internal_Vector3_Vec3)

        Evergreen.V1.Internal.Constraint.Lock p0 p1 p2 p3 p4 p5 p6 p7 ->
            Evergreen.V2.Internal.Constraint.Lock (p0 |> migrate_Internal_Vector3_Vec3)
                (p1 |> migrate_Internal_Vector3_Vec3)
                (p2 |> migrate_Internal_Vector3_Vec3)
                (p3 |> migrate_Internal_Vector3_Vec3)
                (p4 |> migrate_Internal_Vector3_Vec3)
                (p5 |> migrate_Internal_Vector3_Vec3)
                (p6 |> migrate_Internal_Vector3_Vec3)
                (p7 |> migrate_Internal_Vector3_Vec3)

        Evergreen.V1.Internal.Constraint.Distance p0 ->
            Evergreen.V2.Internal.Constraint.Distance p0


migrate_Internal_Equation_WarmStart : Evergreen.V1.Internal.Equation.WarmStart -> Evergreen.V2.Internal.Equation.WarmStart
migrate_Internal_Equation_WarmStart old =
    { lambda = old.lambda
    , t1 = old.t1 |> migrate_Internal_Vector3_Vec3
    }


migrate_Internal_Material_Material : Evergreen.V1.Internal.Material.Material -> Evergreen.V2.Internal.Material.Material
migrate_Internal_Material_Material old =
    old


migrate_Internal_Matrix3_Mat3 : Evergreen.V1.Internal.Matrix3.Mat3 -> Evergreen.V2.Internal.Matrix3.Mat3
migrate_Internal_Matrix3_Mat3 old =
    old


migrate_Internal_Vector3_Vec3 : Evergreen.V1.Internal.Vector3.Vec3 -> Evergreen.V2.Internal.Vector3.Vec3
migrate_Internal_Vector3_Vec3 old =
    old


migrate_LineSegment3d_LineSegment3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.LineSegment3d.LineSegment3d units_old coordinates_old -> Evergreen.V2.LineSegment3d.LineSegment3d units_new coordinates_new
migrate_LineSegment3d_LineSegment3d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_LineSegment3d migrate_units migrate_coordinates


migrate_Point3d_Point3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Point3d.Point3d units_old coordinates_old -> Evergreen.V2.Point3d.Point3d units_new coordinates_new
migrate_Point3d_Point3d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_Point3d


migrate_Polyline3d_Polyline3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Polyline3d.Polyline3d units_old coordinates_old -> Evergreen.V2.Polyline3d.Polyline3d units_new coordinates_new
migrate_Polyline3d_Polyline3d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_Polyline3d migrate_units migrate_coordinates


migrate_Quantity_Quantity : Quantity.Quantity number units -> Quantity.Quantity number units2
migrate_Quantity_Quantity old =
    Quantity.unwrap old |> Quantity.unsafe


migrate_Scene3d_Types_BackFaceSetting : Evergreen.V1.Scene3d.Types.BackFaceSetting -> Evergreen.V2.Scene3d.Types.BackFaceSetting
migrate_Scene3d_Types_BackFaceSetting old =
    case old of
        Evergreen.V1.Scene3d.Types.KeepBackFaces ->
            Evergreen.V2.Scene3d.Types.KeepBackFaces

        Evergreen.V1.Scene3d.Types.CullBackFaces ->
            Evergreen.V2.Scene3d.Types.CullBackFaces


migrate_Scene3d_Types_LinearRgb : Evergreen.V1.Scene3d.Types.LinearRgb units_old -> Evergreen.V2.Scene3d.Types.LinearRgb units_new
migrate_Scene3d_Types_LinearRgb old =
    case old of
        Evergreen.V1.Scene3d.Types.LinearRgb p0 ->
            Evergreen.V2.Scene3d.Types.LinearRgb p0


migrate_Scene3d_Types_Material : Evergreen.V1.Scene3d.Types.Material coordinates_old attributes_old -> Evergreen.V2.Scene3d.Types.Material coordinates_new attributes_new
migrate_Scene3d_Types_Material old =
    case old of
        Evergreen.V1.Scene3d.Types.UnlitMaterial p0 p1 ->
            Evergreen.V2.Scene3d.Types.UnlitMaterial (p0 |> migrate_Scene3d_Types_TextureMap)
                (p1 |> migrate_Scene3d_Types_Texture identity)

        Evergreen.V1.Scene3d.Types.EmissiveMaterial p0 p1 p2 ->
            Evergreen.V2.Scene3d.Types.EmissiveMaterial (p0 |> migrate_Scene3d_Types_TextureMap)
                (p1 |> migrate_Scene3d_Types_Texture migrate_Scene3d_Types_LinearRgb)
                p2

        Evergreen.V1.Scene3d.Types.LambertianMaterial p0 p1 p2 p3 ->
            Evergreen.V2.Scene3d.Types.LambertianMaterial (p0 |> migrate_Scene3d_Types_TextureMap)
                (p1 |> migrate_Scene3d_Types_Texture migrate_Scene3d_Types_LinearRgb)
                (p2 |> migrate_Scene3d_Types_Texture identity)
                (p3 |> migrate_Scene3d_Types_NormalMap)

        Evergreen.V1.Scene3d.Types.PbrMaterial p0 p1 p2 p3 p4 p5 ->
            Evergreen.V2.Scene3d.Types.PbrMaterial (p0 |> migrate_Scene3d_Types_TextureMap)
                (p1 |> migrate_Scene3d_Types_Texture migrate_Scene3d_Types_LinearRgb)
                (p2 |> migrate_Scene3d_Types_Texture identity)
                (p3 |> migrate_Scene3d_Types_Texture identity)
                (p4 |> migrate_Scene3d_Types_Texture identity)
                (p5 |> migrate_Scene3d_Types_NormalMap)


migrate_Scene3d_Types_Mesh : (coordinates_old -> coordinates_new) -> Evergreen.V1.Scene3d.Types.Mesh coordinates_old attributes_old -> Evergreen.V2.Scene3d.Types.Mesh coordinates_new attributes_new
migrate_Scene3d_Types_Mesh migrate_coordinates old =
    case old of
        Evergreen.V1.Scene3d.Types.EmptyMesh ->
            Evergreen.V2.Scene3d.Types.EmptyMesh

        Evergreen.V1.Scene3d.Types.Triangles p0 p1 p2 p3 ->
            Evergreen.V2.Scene3d.Types.Triangles (p0 |> migrate_BoundingBox3d_BoundingBox3d identity migrate_coordinates)
                (p1 |> List.map (migrate_Triangle3d_Triangle3d identity migrate_coordinates))
                p2
                (p3 |> migrate_Scene3d_Types_BackFaceSetting)

        Evergreen.V1.Scene3d.Types.Facets p0 p1 p2 p3 ->
            Evergreen.V2.Scene3d.Types.Facets (p0 |> migrate_BoundingBox3d_BoundingBox3d identity migrate_coordinates)
                (p1 |> List.map (migrate_Triangle3d_Triangle3d identity migrate_coordinates))
                p2
                (p3 |> migrate_Scene3d_Types_BackFaceSetting)

        Evergreen.V1.Scene3d.Types.Indexed p0 p1 p2 p3 ->
            Evergreen.V2.Scene3d.Types.Indexed (p0 |> migrate_BoundingBox3d_BoundingBox3d identity migrate_coordinates)
                (p1 |> migrate_TriangularMesh_TriangularMesh (migrate_Point3d_Point3d identity migrate_coordinates))
                p2
                (p3 |> migrate_Scene3d_Types_BackFaceSetting)

        Evergreen.V1.Scene3d.Types.MeshWithNormals p0 p1 p2 p3 ->
            Evergreen.V2.Scene3d.Types.MeshWithNormals (p0 |> migrate_BoundingBox3d_BoundingBox3d identity migrate_coordinates)
                (p1
                    |> migrate_TriangularMesh_TriangularMesh
                        (\rec ->
                            { position = rec.position |> migrate_Point3d_Point3d identity migrate_coordinates
                            , normal = rec.normal |> migrate_Vector3d_Vector3d identity migrate_coordinates
                            }
                        )
                )
                p2
                (p3 |> migrate_Scene3d_Types_BackFaceSetting)

        Evergreen.V1.Scene3d.Types.MeshWithUvs p0 p1 p2 p3 ->
            Evergreen.V2.Scene3d.Types.MeshWithUvs (p0 |> migrate_BoundingBox3d_BoundingBox3d identity migrate_coordinates)
                (p1
                    |> migrate_TriangularMesh_TriangularMesh
                        (\rec ->
                            { position = rec.position |> migrate_Point3d_Point3d identity migrate_coordinates
                            , uv = rec.uv
                            }
                        )
                )
                p2
                (p3 |> migrate_Scene3d_Types_BackFaceSetting)

        Evergreen.V1.Scene3d.Types.MeshWithNormalsAndUvs p0 p1 p2 p3 ->
            Evergreen.V2.Scene3d.Types.MeshWithNormalsAndUvs (p0 |> migrate_BoundingBox3d_BoundingBox3d identity migrate_coordinates)
                (p1
                    |> migrate_TriangularMesh_TriangularMesh
                        (\rec ->
                            { position = rec.position |> migrate_Point3d_Point3d identity migrate_coordinates
                            , normal = rec.normal |> migrate_Vector3d_Vector3d identity migrate_coordinates
                            , uv = rec.uv
                            }
                        )
                )
                p2
                (p3 |> migrate_Scene3d_Types_BackFaceSetting)

        Evergreen.V1.Scene3d.Types.MeshWithTangents p0 p1 p2 p3 ->
            Evergreen.V2.Scene3d.Types.MeshWithTangents (p0 |> migrate_BoundingBox3d_BoundingBox3d identity migrate_coordinates)
                (p1
                    |> migrate_TriangularMesh_TriangularMesh
                        (\rec ->
                            { position = rec.position |> migrate_Point3d_Point3d identity migrate_coordinates
                            , normal = rec.normal |> migrate_Vector3d_Vector3d identity migrate_coordinates
                            , uv = rec.uv
                            , tangent = rec.tangent |> migrate_Vector3d_Vector3d identity migrate_coordinates
                            , tangentBasisIsRightHanded = rec.tangentBasisIsRightHanded
                            }
                        )
                )
                p2
                (p3 |> migrate_Scene3d_Types_BackFaceSetting)

        Evergreen.V1.Scene3d.Types.LineSegments p0 p1 p2 ->
            Evergreen.V2.Scene3d.Types.LineSegments (p0 |> migrate_BoundingBox3d_BoundingBox3d identity migrate_coordinates)
                (p1 |> List.map (migrate_LineSegment3d_LineSegment3d identity migrate_coordinates))
                p2

        Evergreen.V1.Scene3d.Types.Polyline p0 p1 p2 ->
            Evergreen.V2.Scene3d.Types.Polyline (p0 |> migrate_BoundingBox3d_BoundingBox3d identity migrate_coordinates)
                (p1 |> migrate_Polyline3d_Polyline3d identity migrate_coordinates)
                p2

        Evergreen.V1.Scene3d.Types.Points p0 p1 p2 p3 ->
            Evergreen.V2.Scene3d.Types.Points (p0 |> migrate_BoundingBox3d_BoundingBox3d identity migrate_coordinates)
                p1
                (p2 |> List.map (migrate_Point3d_Point3d identity migrate_coordinates))
                p3


migrate_Scene3d_Types_NormalMap : Evergreen.V1.Scene3d.Types.NormalMap -> Evergreen.V2.Scene3d.Types.NormalMap
migrate_Scene3d_Types_NormalMap old =
    case old of
        Evergreen.V1.Scene3d.Types.NoNormalMap ->
            Evergreen.V2.Scene3d.Types.NoNormalMap

        Evergreen.V1.Scene3d.Types.NormalMap p0 ->
            Evergreen.V2.Scene3d.Types.NormalMap
                { url = p0.url
                , options = p0.options
                , data = p0.data
                , format = p0.format |> migrate_Scene3d_Types_NormalMapFormat
                }


migrate_Scene3d_Types_NormalMapFormat : Evergreen.V1.Scene3d.Types.NormalMapFormat -> Evergreen.V2.Scene3d.Types.NormalMapFormat
migrate_Scene3d_Types_NormalMapFormat old =
    case old of
        Evergreen.V1.Scene3d.Types.OpenglFormat ->
            Evergreen.V2.Scene3d.Types.OpenglFormat

        Evergreen.V1.Scene3d.Types.DirectxFormat ->
            Evergreen.V2.Scene3d.Types.DirectxFormat


migrate_Scene3d_Types_Texture : (value_old -> value_new) -> Evergreen.V1.Scene3d.Types.Texture value_old -> Evergreen.V2.Scene3d.Types.Texture value_new
migrate_Scene3d_Types_Texture migrate_value old =
    case old of
        Evergreen.V1.Scene3d.Types.Constant p0 ->
            Evergreen.V2.Scene3d.Types.Constant (p0 |> migrate_value)

        Evergreen.V1.Scene3d.Types.Texture p0 ->
            Evergreen.V2.Scene3d.Types.Texture p0


migrate_Scene3d_Types_TextureMap : Evergreen.V1.Scene3d.Types.TextureMap -> Evergreen.V2.Scene3d.Types.TextureMap
migrate_Scene3d_Types_TextureMap old =
    case old of
        Evergreen.V1.Scene3d.Types.UseMeshUvs ->
            Evergreen.V2.Scene3d.Types.UseMeshUvs


migrate_Shapes_Capsule_Capsule : Evergreen.V1.Shapes.Capsule.Capsule -> Evergreen.V2.Shapes.Capsule.Capsule
migrate_Shapes_Capsule_Capsule old =
    { radius = old.radius
    , halfLength = old.halfLength
    , axis = old.axis |> migrate_Internal_Vector3_Vec3
    , position = old.position |> migrate_Internal_Vector3_Vec3
    , volume = old.volume
    , inertia = old.inertia |> migrate_Internal_Matrix3_Mat3
    }


migrate_Shapes_Convex_FaceGroup : Evergreen.V1.Shapes.Convex.FaceGroup -> Evergreen.V2.Shapes.Convex.FaceGroup
migrate_Shapes_Convex_FaceGroup old =
    case old of
        Evergreen.V1.Shapes.Convex.OneSidedFace p0 p1 p2 p3 p4 p5 ->
            Evergreen.V2.Shapes.Convex.OneSidedFace (p0 |> migrate_Internal_Vector3_Vec3)
                p1
                p2
                p3
                p4
                p5

        Evergreen.V1.Shapes.Convex.TwoSidedFace p0 p1 p2 p3 p4 p5 ->
            Evergreen.V2.Shapes.Convex.TwoSidedFace (p0 |> migrate_Internal_Vector3_Vec3)
                p1
                p2
                (p3 |> migrate_Internal_Vector3_Vec3)
                p4
                p5


migrate_Shapes_Convex_Obb : Evergreen.V1.Shapes.Convex.Obb -> Evergreen.V2.Shapes.Convex.Obb
migrate_Shapes_Convex_Obb old =
    case old of
        Evergreen.V1.Shapes.Convex.Box p0 p1 p2 p3 ->
            Evergreen.V2.Shapes.Convex.Box (p0 |> migrate_Internal_Vector3_Vec3)
                (p1 |> migrate_Internal_Vector3_Vec3)
                (p2 |> migrate_Internal_Vector3_Vec3)
                (p3 |> migrate_Internal_Vector3_Vec3)

        Evergreen.V1.Shapes.Convex.NotBox p0 p1 p2 p3 ->
            Evergreen.V2.Shapes.Convex.NotBox p0 p1 p2 p3


migrate_Shapes_Plane_Plane : Evergreen.V1.Shapes.Plane.Plane -> Evergreen.V2.Shapes.Plane.Plane
migrate_Shapes_Plane_Plane old =
    { normal = old.normal |> migrate_Internal_Vector3_Vec3
    , position = old.position |> migrate_Internal_Vector3_Vec3
    }


migrate_Shapes_Sphere_Sphere : Evergreen.V1.Shapes.Sphere.Sphere -> Evergreen.V2.Shapes.Sphere.Sphere
migrate_Shapes_Sphere_Sphere old =
    { radius = old.radius
    , position = old.position |> migrate_Internal_Vector3_Vec3
    , volume = old.volume
    , inertia = old.inertia |> migrate_Internal_Matrix3_Mat3
    }


migrate_Sphere3d_Sphere3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Sphere3d.Sphere3d units_old coordinates_old -> Evergreen.V2.Sphere3d.Sphere3d units_new coordinates_new
migrate_Sphere3d_Sphere3d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_Sphere3d migrate_units migrate_coordinates


migrate_Triangle3d_Triangle3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Triangle3d.Triangle3d units_old coordinates_old -> Evergreen.V2.Triangle3d.Triangle3d units_new coordinates_new
migrate_Triangle3d_Triangle3d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_Triangle3d migrate_units migrate_coordinates


migrate_TriangularMesh_TriangularMesh : (vertex_old -> vertex_new) -> TriangularMesh.TriangularMesh vertex_old -> TriangularMesh.TriangularMesh vertex_new
migrate_TriangularMesh_TriangularMesh migrate_vertex old =
    old |> TriangularMesh.mapVertices migrate_vertex


migrate_Types_Direction : String -> Evergreen.V2.Types.Direction
migrate_Types_Direction _ =
    Evergreen.V2.Types.Right


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V2.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.UrlClicked p0 ->
            Evergreen.V2.Types.UrlClicked p0

        Evergreen.V1.Types.UrlChanged p0 ->
            Evergreen.V2.Types.UrlChanged p0

        Evergreen.V1.Types.Resize p0 p1 ->
            Evergreen.V2.Types.Resize p0 p1

        Evergreen.V1.Types.BoxMeshLoaded p0 ->
            Evergreen.V2.Types.UserChangedJoinCode ""

        Evergreen.V1.Types.BoxRedTextureLoaded p0 ->
            Evergreen.V2.Types.UserChangedJoinCode ""

        Evergreen.V1.Types.BoxBlueTextureLoaded p0 ->
            Evergreen.V2.Types.UserChangedJoinCode ""

        Evergreen.V1.Types.CylinderMeshLoaded p0 ->
            Evergreen.V2.Types.UserChangedJoinCode ""

        Evergreen.V1.Types.UserChosePlayWithStranger ->
            Evergreen.V2.Types.UserChosePlayWithStranger

        Evergreen.V1.Types.UserChoseHostFriend ->
            Evergreen.V2.Types.UserChoseHostFriend

        Evergreen.V1.Types.UserChangedJoinCode p0 ->
            Evergreen.V2.Types.UserChangedJoinCode p0

        Evergreen.V1.Types.UserChoseJoinFriend ->
            Evergreen.V2.Types.UserChoseJoinFriend

        Evergreen.V1.Types.UserAbandonedWaiting ->
            Evergreen.V2.Types.UserAbandonedWaiting

        Evergreen.V1.Types.Admin_ClickedClearAllMatches ->
            Evergreen.V2.Types.Admin_ClickedClearAllMatches

        Evergreen.V1.Types.GameMessage p0 ->
            Evergreen.V2.Types.GameMessage (p0 |> migrate_Types_GameMsg)


migrate_Types_GameMsg : Evergreen.V1.Types.GameMsg -> Evergreen.V2.Types.GameMsg
migrate_Types_GameMsg old =
    case old of
        Evergreen.V1.Types.Tick p0 ->
            Evergreen.V2.Types.Tick p0

        Evergreen.V1.Types.UserEnteredElevation p0 ->
            Evergreen.V2.Types.UserEnteredElevation p0

        Evergreen.V1.Types.UserEnteredRotation p0 ->
            Evergreen.V2.Types.UserEnteredRotation p0

        Evergreen.V1.Types.UserEnteredForce p0 ->
            Evergreen.V2.Types.UserEnteredForce p0

        Evergreen.V1.Types.UserFiredBall ->
            Evergreen.V2.Types.UserFiredBall

        Evergreen.V1.Types.UserStartedMovingCamera p0 ->
            Evergreen.V2.Types.UserStartedMovingCamera (p0 |> migrate_Types_Direction)

        Evergreen.V1.Types.UserRequestedNewGame ->
            Evergreen.V2.Types.UserRequestedNewGame

        Evergreen.V1.Types.UserRequestedLeaveMatch ->
            Evergreen.V2.Types.UserRequestedLeaveMatch


migrate_Types_Stage : Evergreen.V1.Types.Stage -> Evergreen.V2.Types.Stage
migrate_Types_Stage old =
    case old of
        Evergreen.V1.Types.Aiming ->
            Evergreen.V2.Types.Aiming

        Evergreen.V1.Types.Simulating ->
            Evergreen.V2.Types.Simulating

        Evergreen.V1.Types.GameOver p0 ->
            Evergreen.V2.Types.GameOver (p0 |> migrate_Types_Turn)


migrate_Types_Turn : Evergreen.V1.Types.Turn -> Evergreen.V2.Types.Turn
migrate_Types_Turn old =
    case old of
        Evergreen.V1.Types.Red ->
            Evergreen.V2.Types.Red

        Evergreen.V1.Types.Blue ->
            Evergreen.V2.Types.Blue


migrate_Vector3d_Vector3d : (units_old -> units_new) -> (coordinates_old -> coordinates_new) -> Evergreen.V1.Vector3d.Vector3d units_old coordinates_old -> Evergreen.V2.Vector3d.Vector3d units_new coordinates_new
migrate_Vector3d_Vector3d migrate_units migrate_coordinates old =
    old |> migrate_Geometry_Types_Vector3d
